import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { AnimatePresence, motion } from 'framer-motion'
import { useState } from 'react'
// components
import { Hints } from '@/components/Hints/Hints';
import { Input } from '@/components/Input/Input';
import { Message } from '@/components/Message/Message'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [visible, setVisible] = useState(false);
    const [searchTerm, setSearchTerm] = useState('');
    const [message, setMessage] = useState(<></>);
    const [showMessage, setShowMessage] = useState(false);
   
    const toggleVisible = () => {
        setVisible(!visible);
      }
  
    const animations = {
    headerAppear: {
        opacity: [0,1],
        transition: {delay: 0.4}
    },
    headerDisappear: {
        opacity: [1,0],
        transition: {delay: 0}
    },
  }
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.top}>
            <AnimatePresence
                mode="wait">
                {!visible && (<motion.h1
                    key="header1"
                    variants={animations}
                    animate="headerAppear"
                    exit="headerDisappear"
                    >
                        click
                        </motion.h1>
                    )}
                    {visible && (<motion.h1
                    key="header2"
                    variants={animations}
                    animate="headerAppear"
                    exit="headerDisappear"
                    >
                        Enter command
                    </motion.h1>)}
            </AnimatePresence>
        </div>
        <div className={styles.inputContainer}>
            <Input 
                visible={visible}
                toggleVisible={toggleVisible}
                searchTerm={searchTerm}
                setSearchTerm={setSearchTerm}
                setMessage={setMessage}
                setShowMessage={setShowMessage}
                />
        </div>
        <div className={styles.hints}>
            <Hints 
                visible={visible}
                setSearchTerm={setSearchTerm}
                setShowMessage={setShowMessage}
                />
         </div>
         <Message 
            message={message}
            showMessage={showMessage}
            />
    </main>
    </>
  )
}
